name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker login
      run:
        docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASSWORD}}
    - name: Build the Docker image
      run: 
        docker build . --file Dockerfile --tag docker-cpp-py:$(date +%s)
    - name: Docker Push
      run:
        docker push ${{secrets.DOCKER_USER}}/docker-cpp-py
        
